name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  run_docker:
    name: test secrets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.DX_NUGET_URL }}
      run: docker build . --file Dockerfile --build-arg DX_NUGET_URL=$SUPER_SECRET --tag some/image:image-api
